#!/bin/bash

#for bluetooth pan connections
#there is cgnat here so no need to open ports
#for emergency connections

#DEPENDENCIES: dnsmasq/iftop/iptables

#run the main thread to use as mid
#run this router to use as router
#one role or the other not both

#turn off predicatable device names in grub
#net.ifnames=0 biosdevname=0

#determine WAN port
WAN=ppp0
WAN_CHECK_1=$(sudo ifconfig -a | grep wwan0 | wc -l)
if [ $WAN_CHECK_1 -gt 0 ]
then
WAN=wwan0
fi
WAN_CHECK_2=$(sudo ifconfig -a | grep usb0 | wc -l)
if [ $WAN_CHECK_2 -gt 0 ]
then
WAN=usb0
fi
WAN_CHECK_2=$(sudo ifconfig -a | grep bnep0 | wc -l)
if [ $WAN_CHECK_2 -gt 0 ]
then
WAN=bnep0
fi
#this gives errors on a console only setup
#if ! kdialog --title "Router" --warningcontinuecancel "Press continue to run the router app"
#if ! zenity --question --text "Press Continue to run the router app"
#then
#exit
#fi

#read -p "Press y to continue" -n 1 -r
#if [[ $REPLY =~ ^[Yy]$ ]]
#then

#set ethernet ip manually
#sudo ifconfig eth0 up
#sudo ifconfig eth0 192.168.5.7

#start cellular connection
#sudo dhclient usb0
#sudo ifconfig $WAN 192.168.1.2
#sudo ifconfig $WAN 192.168.1.163
#sudo route add default gw 192.168.1.1
#sudo sh -c "echo -e 'nameserver 209.18.47.61\nnameserver 209.18.47.62' > /etc/resolv.conf"
#sudo sh -c "echo 'nameserver 208.67.222.222\nnameserver 208.67.220.220' > /etc/resolv.conf"

#pass traffic from subnet to subnet
sudo sh -c "echo '1' >> /proc/sys/net/ipv4/ip_forward"

#don't block any traffic to or from the lan specifically
#an inverse rule does not make sense here
#because things go to and from ppp0 freely because it is router
#no it is supposed to block all on wan until a rule is made
#redundant - accepted by default
#sudo iptables -A FORWARD -i eth0 -j ACCEPT
#sudo iptables -A FORWARD -o eth0 -j ACCEPT

#all traffic is translated going out of ppp0
sudo iptables -t nat -A POSTROUTING -o $WAN -j MASQUERADE
#try this too for newer systems just in case
sudo iptables-legacy -t nat -A POSTROUTING -o $WAN -j MASQUERADE

#traffic forwarding which specifically unblocks also?
#sudo iptables -t nat -A PREROUTING -i ppp0 -p tcp --dport 80 -J DNAT--to 192.168.1.10:80

echo "Starting Router"
sleep 3

sudo iftop -p -i $WAN

echo "Shutting Down Router"
#sudo ifconfig eth0 0.0.0.0
#sudo ifconfig eth0 down
#sudo ifconfig $WAN down
sudo sh -c "echo '0' >> /proc/sys/net/ipv4/ip_forward"

#fi #read

